[package]
name = "dyn-experiments"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tuple_list = "0.1.3"
petgraph = "0.6.0"
smallvec = "1.8.0"
